project:
  name: spotify-gb-classifier
  seed: 42

data:
  processed_path: data/processed/spotify_classification.csv
  target: is_popular
  features:
    - bpm
    - danceability_%
    - valence_%
    - energy_%
    - acousticness_%
    - instrumentalness_%
    - liveness_%
    - speechiness_%

training:
  test_size: 0.2

model:
  type: gradient_boosting
  params:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 5
    random_state: 42

mlflow:
  experiment_name: spotify-classification