project:
  name: spotify-experiment-1
  seed: 42

data:
  processed_path: data/processed/spotify_clean.csv
  target: log_streams
  features:
    - bpm
    - danceability_%
    - valence_%
    - energy_%
    - acousticness_%
    - instrumentalness_%
    - liveness_%
    - speechiness_%

training:
  test_size: 0.2

model:
  type: random_forest
  params:
    n_estimators: 100
    max_depth: 6
    min_samples_split: 10
    random_state: 42
    n_jobs: -1

mlflow:
  experiment_name: spotify-experiment-1